language: python 
python:
  - "3.6"

services: 
  - postgresql

env:
  matrix:
    - DJANGO=2.1 DB=postgres
  global:
    - SECRET_KEY=not_so_secret
      B_DATABASE_URL="postgres://postgres@localhost/test_db"
      ALLOWED_HOSTS= "localhost"
      SENTRY_DSN=""

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database test_db;' -U postgres

script:
  - python manage.py test